/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/halloween_haunted_house.glb --transform
Author: Karthik Naidu (https://sketchfab.com/Karthik_TS)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/halloween-haunted-house-402b277372424e75b4c7aec309889dda
Title: Halloween Haunted House
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./public/halloween_haunted_house-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Grass_lush} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.floating_island} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Chimney} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Door_Amd_windows_emmisivw} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Grave_Stone__stairs} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Housewall} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Pumpkin_Hallowee} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Pumpkin_eyew_n_mouth_glowimg} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Pumpkin_hair} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Roof} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Stones} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Tree_pine} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Tree_stemp} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Wood_plnks} />
      </group>
    </group>
  )
}

useGLTF.preload('./public/halloween_haunted_house-transformed.glb')
