/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 unity.gltf --transform
Author: Anthony Yanez (https://sketchfab.com/paulyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/unity-logo-a9299dd053cb46a0b2dfcffd378f1088
Title: Unity Logo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/unity-transformed.glb')

  return (
    <group {...props} dispose={null}>
      <mesh rotation={[Math.PI/4, -Math.PI / 4, 0]}  geometry={nodes['Unity_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[443.08, -148.06, -34.52]} />
    </group>
  )
}

useGLTF.preload('./public/unity-transformed.glb')
